### ISSUE TITLE
Refactor yaml config a bit to make it cleaner

### ISSUE THREAD

**Issue by adidenko** [wayfair-incubator/telefonistka#15]
## Problem Statement

IMHO the current config structure is not very intuitive with those lists of lists:

```yaml
  - sourcePath: "clusters/staging/[^/]*/[^/]*" # This will start a promotion to prod from any "staging" path
    conditions:
      prHasLabels:
        - "quick_promotion" # This flow will run only if PR has "quick_promotion" label, see targetPaths below
    targetPaths:
      -
        - "clusters/prod/us-west1/c2" # First PR for only a single cluster
      -
        - "clusters/prod/europe-west3/c2" # 2nd PR will sync all 4 remaining clusters
        - "clusters/prod/europe-west4/c2"
        - "clusters/prod/us-central1/c2"
        - "clusters/prod/us-east4/c2"
  ```

## Proposed Solution

Refactor the `targetPaths` struct a bit, to make it more intuitive

```yaml
  - sourcePath: "clusters/staging/[^/]*/[^/]*" # This will start a promotion to prod from any "staging" path
    conditions:
      prHasLabels:
        - "quick_promotion" # This flow will run only if PR has "quick_promotion" label, see targetPaths below
    createSeparatePromotionPRForEach:
      - targetPaths:
        - "clusters/prod/us-west1/c2" # First PR for only a single cluster
      - targetPaths:
        - "clusters/prod/europe-west3/c2" # 2nd PR will sync all 4 remaining clusters
        - "clusters/prod/europe-west4/c2"
        - "clusters/prod/us-central1/c2"
        - "clusters/prod/us-east4/c2"
```

The `createStandalonePromotionPRForEach` is a subject to change, obviously. But I hope the idea is clear.

## Alternatives Considered

Leaving everything as is 😄 

## Additional Context

None
