### ISSUE TITLE
Support different directory structures

### ISSUE THREAD

**Issue by dudicoco** [wayfair-incubator/telefonistka#202]
## Problem Statement

The current implementation only supports the component name after the environment name: `dev/us-east-1/componenent-1/`.

We are using a different structure which I believe is also very common: `team-1/component-1/dev_us-east-1/`.

It seems that Telefonistka cannot handle this file structure.

## Additional Context

Telefonistka.yaml:
```yaml
promotionPaths:
- sourcePath: workspace/
  promotionPrs:
  - targetPaths:
    - devops/.*/dev_us-east-1/
- sourcePath: devops/.*/stage_us-east-1/ # This will start a promotion to prod from any "stage" path
  conditions:
    prHasLabels:
    - quick_promotion # This flow will run only if PR has "quick_promotion" label, see targetPaths below
  promotionPrs:
  - targetPaths:
    - devops/.*/prod_ap-southeast-2/ # First PR for only a single cluster
  - targetPaths:
    - devops/.*/prod_us-east-1/ # 2nd PR will sync all remaining clusters
    - devops/.*/prod_eu-central-1/
- sourcePath: devops/.*/stage_us-east-1 # This flow will run on PR without "quick_promotion" label
  promotionPrs:
  - targetPaths:
    - devops/.*/prod_ap-southeast-2/ # Each cluster will have its own promotion PR
  - targetPaths:
    - devops/.*/prod_us-east-1/
  - targetPaths:
    - devops/.*/prod_eu-central-1/
dryRunMode: false
autoApprovePromotionPrs: false
toggleCommitStatus:
  override-terrafrom-pipeline: github-action-terraform
```

File structure:
```sh
.
├── LICENSE
├── README.md
├── devops
│   └── amazing-app
│       ├── dev_us-east-1
│       │   └── values.yaml
│       ├── prod_ap-southeast-2
│       │   └── values.yaml
│       ├── prod_eu-central-1
│       │   └── values.yaml
│       ├── prod_us-east-1
│       │   └── values.yaml
│       └── stage_us-east-1
│           └── values.yaml
├── telefonistka.yaml
└── workspace
    └── amazing-app
        └── values.yaml
```

Example PR: https://github.com/dudicoco/telefonistka-actions-example/pull/14
Example action: https://github.com/dudicoco/telefonistka-actions-example/actions/runs/10836288434/job/30069715676?pr=14
