### ISSUE TITLE
Auto-generate the first PR when a dependency (container image, another Git repo, etc) is updated

### ISSUE THREAD

**Issue by akorzy-pl** [wayfair-incubator/telefonistka#62]
## Problem Statement

Currently the first PR to the workspace needs to be created manually. However, I would like a PR to be created automatically whenever one of the declared dependencies is updated.

## Proposed Solution

For example, I imagine that there would be a configuration file where I could declare the dependencies/subscriptions of a given application (such as another Git repo/branch or a container image path/tag regex) and whenever the dependency is updated, Telefonistka would create a PR with a new version of the dependency (a new commit ID or tag of the dependency).

## Alternatives Considered

Automatically creating the first PR could be done by an independent GitHub workflow/app, but I believe it fits well into Telefonistka. 

## Additional Context

[Kargo](https://github.com/akuity/kargo/blob/main/docs/docs/15-concepts.md) allows the user to define the list of subscriptions:

```
  subscriptions:
    repos:
      git:
      - repoURL: https://github.com/example/kargo-demo-gitops.git
        branch: main
      images:
      - repoURL: nginx
        semverConstraint: ^1.23.0
```

I'm thinking about Telefonistka having a configuration file stored in Git with contents similar to the above.
