### ISSUE TITLE
Fails on dry-run mode

### ISSUE THREAD

**Issue by krzwiatrzyk** [wayfair-incubator/telefonistka#97]
## Description

Please provide a description of the problem.
![image](https://github.com/wayfair-incubator/telefonistka/assets/52850037/fe19a17a-3efc-40a2-9c62-5caebb254cc3)

## Expected Behaviour

Setup telefonistka based on instruction:
```
name: Telefonistka

on:
  pull_request:
    types: 
      - closed
      - opened
      - synchronize
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  telefonistka:
    runs-on: ubuntu-latest
    steps:
      - uses:  Oded-B/telefonistka-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

```
promotionPaths:
  - sourcePath: "configs/staging/[^/]*"
    promotionPrs:
      - targetPaths:
        - configs/production
dryRunMode: true
autoApprovePromotionPrs: true

```

## Actual Behaviour

Error after merge

## Affected Version

Current

## Steps to Reproduce
 
 Follow instruction
 
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/wayfair-incubator/telefonistka/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by krzwiatrzyk** [comment]
And FYI, i checked if this tries to find those in local files and it doesn't, setting those files in repo won't change output.

**Comment by Oded-B** [comment]
I was able to reproduce.
GitHub action override the default docker work dir with `--workdir /github/workspace ` so the relative path reference fails.
Hopefully I can force the working dir in the GH action yaml (as I prefer to keep using relative path)

**Comment by Oded-B** [comment]
https://github.com/actions/runner/issues/878 😭 
And I use a "scratch" container so I can't "cd" my way around this.
I'll have to allow overriding the template dir(or files) via environment variables or something like that

**Comment by Oded-B** [comment]
Please test the `Set-TEMPLATES_PATH-to-support-GHA-workdir-override` branch of the GH action repo  and let me know.
example config:

```
jobs:
  telefonistka:
    runs-on: ubuntu-latest
    steps:
      - uses:  Oded-B/telefonistka-action@Set-TEMPLATES_PATH-to-support-GHA-workdir-override
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
